"""your message

Revision ID: 3f8848431bbd
Revises: a9799973909e
Create Date: 2024-04-08 08:31:25.681962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8848431bbd'
down_revision = 'a9799973909e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
